import type { Customer, Appointment, Todo, Lead, Opportunity, Case } from './types';

export const dummyCustomers: Customer[] = [
  {
    id: '1',
    name: 'Alice Wonderland',
    email: 'alice@example.com',
    phone: '555-0101',
    company: 'Wonderland Inc.',
    avatarUrl: 'https://placehold.co/100x100/A779E9/FFFFFF.png?text=AW',
    revenue: 12000,
    expenses: 3000,
    industry: 'Technology',
    website: 'https://wonderland.example.com',
    annualRevenue: 150000,
    employeeCount: 25,
    accountType: 'customer',
  },
  {
    id: '2',
    name: 'Bob The Builder',
    email: 'bob@example.com',
    phone: '555-0102',
    company: 'Builders Co.',
    avatarUrl: 'https://placehold.co/100x100/667EEA/FFFFFF.png?text=BB',
    revenue: 25000,
    expenses: 10000,
    industry: 'Construction',
    website: 'https://builders.example.com',
    annualRevenue: 500000,
    employeeCount: 50,
    accountType: 'customer',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    phone: '555-0103',
    company: 'Peanuts LLC',
    avatarUrl: 'https://placehold.co/100x100/FBBF24/FFFFFF.png?text=CB',
    revenue: 8000,
    expenses: 2500,
    industry: 'Entertainment',
    website: 'https://peanuts.example.com',
    annualRevenue: 100000,
    employeeCount: 15,
    accountType: 'customer',
  },
  {
    id: '4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    phone: '555-0104',
    company: 'Themyscira Solutions',
    avatarUrl: 'https://placehold.co/100x100/EF4444/FFFFFF.png?text=DP',
    revenue: 30000,
    expenses: 7000,
    industry: 'Consulting',
    website: 'https://themyscira.example.com',
    annualRevenue: 750000,
    employeeCount: 35,
    accountType: 'customer',
  },
  {
    id: '5',
    name: 'Edward Scissorhands',
    email: 'edward@example.com',
    phone: '555-0105',
    company: 'Artful Cuts',
    avatarUrl: 'https://placehold.co/100x100/3B82F6/FFFFFF.png?text=ES',
    revenue: 15000,
    expenses: 4500,
    industry: 'Creative Services',
    website: 'https://artfulcuts.example.com',
    annualRevenue: 200000,
    employeeCount: 12,
    accountType: 'partner',
  },
];

const today = new Date();
const tomorrow = new Date(today);
tomorrow.setDate(today.getDate() + 1);
const nextWeek = new Date(today);
nextWeek.setDate(today.getDate() + 7);
const yesterday = new Date(today);
yesterday.setDate(today.getDate() -1);


export const dummyAppointments: Appointment[] = [
  {
    id: 'apt1',
    title: 'Meeting with Alice',
    date: today,
    customerId: '1',
    customerName: 'Alice Wonderland',
    description: 'Discuss project proposal.',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 'apt2',
    title: 'Call with Bob',
    date: today,
    customerId: '2',
    customerName: 'Bob The Builder',
    description: 'Follow up on construction plan.',
    startTime: '14:00',
    endTime: '14:30',
  },
  {
    id: 'apt3',
    title: 'Project Kickoff - Charlie',
    date: tomorrow,
    customerId: '3',
    customerName: 'Charlie Brown',
    description: 'Initial project discussion.',
    startTime: '09:00',
    endTime: '10:00',
  },
  {
    id: 'apt4',
    title: 'Strategy Session - Diana',
    date: nextWeek,
    customerId: '4',
    customerName: 'Diana Prince',
    description: 'Plan Q3 marketing strategy.',
    startTime: '11:00',
    endTime: '12:30',
  },
  {
    id: 'apt5',
    title: 'Design Review - Edward',
    date: yesterday,
    customerId: '5',
    customerName: 'Edward Scissorhands',
    description: 'Review latest design mockups.',
    startTime: '15:00',
    endTime: '16:00',
  },
];

export const dummyTodos: Todo[] = [
  { id: 'todo1', task: 'Follow up with Alice', completed: false, dueDate: tomorrow },
  { id: 'todo2', task: 'Prepare presentation for Bob', completed: true, dueDate: today },
  { id: 'todo3', task: 'Send invoice to Charlie', completed: false },
  { id: 'todo4', task: 'Research new CRM features', completed: false, dueDate: nextWeek },
  { id: 'todo5', task: 'Update website portfolio', completed: true },
];

export const dummyLeads: Lead[] = [
  {
    id: 'lead1',
    name: 'Frank Castle',
    email: 'frank@vigilante.com',
    phone: '555-0201',
    company: 'Vigilante Corp',
    title: 'Security Director',
    source: 'website',
    status: 'new',
    rating: 'hot',
    estimatedValue: 50000,
    notes: 'Interested in enterprise security solutions',
    createdAt: today,
  },
  {
    id: 'lead2',
    name: 'Gina Rodriguez',
    email: 'gina@startup.io',
    phone: '555-0202',
    company: 'Startup Innovations',
    title: 'CEO',
    source: 'referral',
    status: 'contacted',
    rating: 'warm',
    estimatedValue: 35000,
    notes: 'Looking for CRM solutions for growing team',
    createdAt: yesterday,
  },
  {
    id: 'lead3',
    name: 'Henry Thompson',
    email: 'henry@oldschool.biz',
    phone: '555-0203',
    company: 'Traditional Industries',
    title: 'Operations Manager',
    source: 'trade-show',
    status: 'qualified',
    rating: 'cold',
    estimatedValue: 20000,
    notes: 'Needs time to evaluate options',
    createdAt: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'lead4',
    name: 'Isabella Martinez',
    email: 'isabella@techforward.com',
    phone: '555-0204',
    company: 'TechForward',
    title: 'VP of Sales',
    source: 'social-media',
    status: 'contacted',
    rating: 'hot',
    estimatedValue: 75000,
    notes: 'Ready to make decision soon',
    createdAt: tomorrow,
  },
];

export const dummyOpportunities: Opportunity[] = [
  {
    id: 'opp1',
    name: 'Enterprise CRM Deal - Wonderland',
    accountId: '1',
    accountName: 'Wonderland Inc.',
    value: 45000,
    stage: 'proposal',
    probability: 60,
    expectedCloseDate: new Date(today.getTime() + 15 * 24 * 60 * 60 * 1000),
    description: 'Full CRM implementation with custom integrations',
    contactName: 'Alice Wonderland',
    createdAt: new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp2',
    name: 'Construction Management Suite - Builders',
    accountId: '2',
    accountName: 'Builders Co.',
    value: 80000,
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000),
    description: 'Project management tools with field service features',
    contactName: 'Bob The Builder',
    createdAt: new Date(today.getTime() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp3',
    name: 'Marketing Automation - Peanuts',
    accountId: '3',
    accountName: 'Peanuts LLC',
    value: 25000,
    stage: 'qualification',
    probability: 30,
    expectedCloseDate: new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000),
    description: 'Email marketing and campaign management',
    contactName: 'Charlie Brown',
    createdAt: new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp4',
    name: 'Consulting Services Package - Themyscira',
    accountId: '4',
    accountName: 'Themyscira Solutions',
    value: 120000,
    stage: 'closed-won',
    probability: 100,
    expectedCloseDate: yesterday,
    description: 'Annual consulting retainer with priority support',
    contactName: 'Diana Prince',
    createdAt: new Date(today.getTime() - 45 * 24 * 60 * 60 * 1000),
    closedAt: yesterday,
  },
  {
    id: 'opp5',
    name: 'Design Tools Integration - Artful',
    accountId: '5',
    accountName: 'Artful Cuts',
    value: 15000,
    stage: 'closed-lost',
    probability: 0,
    expectedCloseDate: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000),
    description: 'Integration with creative design tools',
    contactName: 'Edward Scissorhands',
    createdAt: new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000),
    closedAt: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
];

export const dummyCases: Case[] = [
  {
    id: 'case1',
    title: 'Unable to access dashboard',
    customerId: '1',
    customerName: 'Alice Wonderland',
    priority: 'high',
    status: 'in-progress',
    category: 'technical',
    description: 'User reports intermittent login issues and dashboard not loading',
    createdAt: today,
    assignedTo: 'Support Team',
  },
  {
    id: 'case2',
    title: 'Billing discrepancy for last month',
    customerId: '2',
    customerName: 'Bob The Builder',
    priority: 'medium',
    status: 'waiting',
    category: 'billing',
    description: 'Customer questions charges on latest invoice',
    createdAt: yesterday,
    assignedTo: 'Finance Team',
  },
  {
    id: 'case3',
    title: 'Request for feature enhancement',
    customerId: '3',
    customerName: 'Charlie Brown',
    priority: 'low',
    status: 'new',
    category: 'request',
    description: 'Customer requesting additional reporting capabilities',
    createdAt: today,
  },
  {
    id: 'case4',
    title: 'Data export not working',
    customerId: '4',
    customerName: 'Diana Prince',
    priority: 'critical',
    status: 'resolved',
    category: 'technical',
    description: 'Export to CSV function throwing errors',
    createdAt: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000),
    resolvedAt: yesterday,
    assignedTo: 'Engineering Team',
  },
  {
    id: 'case5',
    title: 'Training session request',
    customerId: '5',
    customerName: 'Edward Scissorhands',
    priority: 'medium',
    status: 'closed',
    category: 'general',
    description: 'Request for onboarding session for new team members',
    createdAt: new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000),
    resolvedAt: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000),
    assignedTo: 'Customer Success',
  },
];
